image: node:latest

cache:
  paths:
    - node_modules/

pages:
  script:
    - npm install
    - REACT_APP_API_URL=https://chronicle-back-end.herokuapp.com/api
    - npm run build
    - mv build .public
    - rm -rf public
    - mv .public public
  artifacts:
    expire_in: 1 hour
    paths:
      - public
  only:
    - master